name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - '**'

env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  GOOGLE_SERVICES_JSON_DEV  : ${{ secrets.GOOGLE_SERVICES_JSON_DEV  }}

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access SPOTIFY_CLIENT_ID
        run: echo $SPOTIFY_CLIENT_ID | base64 --decode --ignore-garbage > ./local.properties
      - name: Access GOOGLE_SERVICES_JSON_DEV
        run: echo $GOOGLE_SERVICES_JSON_DEV   | base64 --decode --ignore-garbage > ./app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Lint
        run: ./gradlew lint

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access SPOTIFY_CLIENT_ID
        run: echo $SPOTIFY_CLIENT_ID | base64 --decode --ignore-garbage > ./local.properties
      - name: Access GOOGLE_SERVICES_JSON_DEV
        run: echo $GOOGLE_SERVICES_JSON_DEV   | base64 --decode --ignore-garbage > ./app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run test
        run: ./gradlew testDebug

  build:

    needs: [lint, test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access SPOTIFY_CLIENT_ID
        run: echo $SPOTIFY_CLIENT_ID | base64 --decode --ignore-garbage > ./local.properties
      - name: Access GOOGLE_SERVICES_JSON_DEV
        run: echo $GOOGLE_SERVICES_JSON_DEV   | base64 --decode --ignore-garbage > ./app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Compile
        run: ./gradlew assembleDebug
